// apps/backend/src/common/constants/error-codes.enum.ts

export enum ErrorCode {
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_INVALID_CURRENT_PASSWORD = 'AUTH_INVALID_CURRENT_PASSWORD',
  ACCOUNT_SOFT_DELETED = 'ACCOUNT_SOFT_DELETED',
}
